config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'pages#home'
  resources :companies, only: [ :new, :create, :destroy, :edit]
  get "company-dashboard", to: "companies#show", as: :company_dashboard
  resources :tasks
  patch "accept-task", to: "tasks#accept_task", as: :accept_task
  get "complete-task", to: "tasks#complete", as: :complete_task
  resources :gazelle_runners
  resources :companies do
    resources :tasks, only: [ :new, :show, :create, :destroy ]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
get 'design', to: 'pages#design'
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :company
  belongs_to :gazelle_runner, optional: true

  belongs_to :task_category, optional: true
  belongs_to :first_location, class_name: 'Location', foreign_key: 'first_location_id', autosave: true
  belongs_to :second_location, class_name: 'Location', foreign_key: 'second_location_id', optional: true, autosave: true


  validates :description, presence: true

  validates :cost_per_hour, presence: true, numericality: true
  validates :task_time, presence: true, numericality: true
  validates :title, presence: true
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.where(state: "pending").reject { |task| task.first_location.nil? }
    # @tasks = Task.where.not(first_location: nil, second_location: nil)

    @markers = @tasks.map do |task|
      {
        lat: task.first_location.latitude,
        lng: task.first_location.longitude#,
        # infoWindow: { content: render_to_string(partial: "/flats/map_box", locals: { flat: flat }) }
      }
    end

    @addresses_for_tasks = {}
    @tasks.each do |task|
      @addresses_for_tasks["#{task.first_location.latitude},#{task.first_location.longitude}"] =
        { name: task.company.name, address: task.first_location.address, final_price: task.cost_per_hour * task.task_time, title: task.title }
    end
  end

  def show
    @company = current_user.company
    @task = Task.find(params[:id])

    if  @task.gazelle_runner && @task.second_location
      @markers = [c_marker, g_marker, p_marker]
      @end_points = {origin: @task.gazelle_runner.address, destination: @task.first_location.address, waypoint: @task.second_location.address}
    elsif @task.second_location
      @markers = [c_marker, p_marker]
      @end_points = { destination: @task.first_location.address, waypoint: @task.second_location.address}
    elsif @task.gazelle_runner
      @markers = [c_marker, g_marker]
      @end_points = {origin: @task.gazelle_runner.address, destination: @task.first_location.address}
    else
      @markers = [c_marker]
    end


  end

  def c_marker
    # this is the marker of the company
  @location = @task.first_location
    {
          lat: @location.latitude,
          lng: @location.longitude,
          icon: ActionController::Base.helpers.asset_path("flag.png")
        }
  end

  def g_marker
    # this is the marker of the gazelle
    @gazelle_runner = @task.gazelle_runner
      gazelle_marker = {
        lat: @gazelle_runner.latitude,
        lng: @gazelle_runner.longitude,
        icon: ActionController::Base.helpers.asset_path("red-gazelle-icon.png")
       }
  end

  def p_marker
    # this is the marker of the pick up location
       @pick_location = @task.second_location
      pick_marker = {
        lat: @pick_location.latitude,
        lng: @pick_location.longitude,
        icon: ActionController::Base.helpers.asset_path("placeholder-blue.png")
      }
  end

  def edit
  end

  def new
    @search_term = params[:search]
    @company = Company.find(params[:company_id])
    @company_marker =  {
        lat: @company.latitude,
        lng: @company.longitude,
        icon: ActionController::Base.helpers.asset_path("flag.png")      }

    @task = Task.new

    @gazelle_runners = GazelleRunner.where.not(latitude: nil, longitude: nil)
    @markers = @gazelle_runners.map do |gazelle_runner|
      {
        lat: gazelle_runner.latitude,
        lng: gazelle_runner.longitude,
        icon: ActionController::Base.helpers.asset_path("red-gazelle-icon.png")
      }

    end

    @names_for_gazelles = {}
    @gazelle_runners.each do |gazelle_runner|
       @names_for_gazelles["#{gazelle_runner.latitude},#{gazelle_runner.longitude}"] =
       { first_name: gazelle_runner.first_name, last_name: gazelle_runner.last_name}
    end

  end

  def accept_task
    @task = Task.find(params[:task])
    @task.gazelle_runner = current_user.gazelle_runner
    @task.state = "assigned"
    @task.save
    redirect_to task_path(@task)
  end

  def create
    @company = Company.find(params[:company_id])
    address = params.dig(:task, :first_location)

    company_location = @company.locations.find_by(address: address)
    company_location = Location.create(address: address, company: @company) unless company_location


    second_address = params.dig(:task, :second_location)
    second_location = Location.create(address: second_address)

    @task = Task.new(task_params)
    @task.company = @company
    @task.first_location = company_location
    @task.second_location = second_location
    @task.photo = "generic.png"

    @task.state = "pending"
    @company.user = current_user
    if @task.save
      redirect_to company_task_path(@company, @task)

    else
      render :new
    end
  end

  def complete
    @task = Task.find(params[:id])
    @task.state = "completed"
    @task.save
    redirect_to task_path(@task)
  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to task_path
  end

  private

  def task_params
    params
      .require(:task)
      .permit( :gazelle_runner_id, :description, :company_id, :cost_per_hour, :task_time, :title, :state)

  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/views/tasks/_company-task-show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 ">
      <div class="order-summary-box">
        <div class="order-summary">
          <h1>ORDER SUMMARY FOR <strong><%= @task.company.name %></strong></h1>
            </div>
            <div class="order-details">
              <p>You have ordered a gazelle to <strong id="input-details" ><%= @task.title %></strong> with additional details <strong id="input-details"><%= @task.description %></strong> </p>
            </div>
            <div class="order-details">
          <p>Your total price for <strong id="input-details"><%= @task.task_time %> hours</strong> will be <strong id="input-details"> <%= task.cost_per_hour * task.task_time %> DKK</strong></p>
        </div>
        <div class="gazelle-card-wrapper">
          <% if @task.state != "pending" %>
            <div class="gazelle-card">
              <div class="gazelle-assigned">
                <p>Your gazelle today will be</p>
                <h2><%= @task.gazelle_runner.first_name %> &nbsp;<i class="fas fa-star"></i> <i class="fas fa-star"></i> <i class="fas fa-star"></i> <i class="fas fa-star"></i> </h2>
              </div>
              <%= cl_image_tag @task.gazelle_runner.photo, class: "gazelle-image" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6">
      <div class="map-wrapper">
        <div class="task-status">
          <% if @task.state == "pending" %>
            <p class="task-status-pending">Your task will be assigned to a gazelle shortly</p>
            <% elsif @task.state == "assigned" %>
            <p class="task-status-assigned">Your gazelle is on its way</p>
              <% else %>
            <p class="task-status-completed">Task has been completed</p>
              <% end %>
          </div>
        <div id="company-show-map" style="height: 450px;" data-markers="<%= @markers.to_json %>" data-end_points="<%= @end_points.to_json %>"></div>
      </div>
    </div>
  </div>
</div>

app/views/tasks/_form.html.erb
<%= simple_form_for [@company, @task] do |f| %>
  <% if @task.errors.any? %>
      <div class="errors-container">
        <ul>
          <% @task.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

  <%= f.input :title, label: "", input_html: { value: @search_term }, placeholder: "Enter task title" %>
  <%= f.input :task_time, label: "", placeholder: "Enter length of task (hours)" %>
  <%= f.input :first_location, label: "",  input_html: {value: @company.address} %>
  <%= f.input :second_location, label: "", placeholder: "Type address if you need something picked up on route" %>
  <%= f.input :description, label: "", placeholder: "Other details" %>
  <%= f.input :cost_per_hour, label: "", placeholder: "Enter pay per hour (DKK)" %>

  <%= f.button :submit, "SUBMIT", class: "btn-solid btn-form" %>
  <% end %>

app/views/tasks/_gazelle-task-show.html.erb
      <div class="col-xs-12 col-sm-12 ">
        <div class= "row">
          <div class="gazelle-order-title">
            <h2>Task summary for <strong><%= @task.gazelle_runner.first_name  %> <%= @task.gazelle_runner.last_name %> </strong></h2>
          </div>
            <div class="gazelle-task-status">
              <% if @task.state == "pending" %>
                <p class="task-status-pending">Task status: <%= @task.state %></p>
                  <% elsif @task.state == "assigned" %>
                <p class="task-status-assigned">Task status: <%= @task.state %></p>
                  <% else %>
                <p class="task-status-completed">Task status: <%= @task.state %></p>
                  <% end %>
            </div>
        </div>
        <div class= "row">
          <div class="gazelle-map-wrapper">
              <div id="company-show-map" style="height: 60vh;" data-markers="<%= @markers.to_json %>"></div>
          </div>
        </div>
        <div class="row">
         <div class="gazelle-order-summary-box">
            <div class="order-details">
              <p>You are required for <strong><%= @task.company.name  %></strong></p>
            </div>
             <div class="gazelle-order-details">
              <p>You are required to <strong><%= @task.description %></strong></p>
            </div>
              <%= link_to "Mark Task as Completed", complete_task_path(id: @task), class: "btn-main text-center" %>
              <%= link_to "Back to Task Center", tasks_path, class: "btn-main text-center" %>
            </div>
          </div>
        </div>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<div class="grid">
  <h1>Task Center</h1>
  <div class= "map-box">
    <div
      id="map"
      data-markers="<%= @markers.to_json %>"
      data-tasks="<%= @addresses_for_tasks.to_json %>">
    </div>
  </div>
  <div class="drop-down-form">
   <%= label_tag("Select a task") %>
    <%= form_tag(accept_task_path , method: :patch) do %>
      <%= select_tag "task",
          options_for_select(@tasks.map { |task| ["#{task.company.name} - #{task.title}", task.id] }) %>
          <br>
      <%= submit_tag("Confirm") %>
    <% end %>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <div class="row">
     <div class="col-xs-6">
        <div class="wrapper-new-task">
          <h1>TASK DETAILS FOR: <strong> <%= @search_term %> </strong> </h1>
           <%= render 'form', task: @task %>
        </div>
      </div>
      <div class="col-xs-6">
        <div class="map-box-task">
          <h1>GAZELLES NEAR YOU:</h1>
          <div id="map-gazelle"
          style="height: 530px;"
          data-markers="<%= @markers.to_json %>"
          data-company="<%= @company_marker.to_json %>"
          data-gazelles="<%= @names_for_gazelles.to_json %>">
          </div>
        </div>
      </div>
  </div>
</div>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <% if current_user.gazelle_runner %>
    <%= render 'gazelle-task-show', task: @task %>
  <% else %>
    <%= render 'company-task-show', task: @task %>
  <% end %>
</div>