config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'pages#home'
  resources :companies, only: [ :new, :create, :destroy, :edit]
  get "company-dashboard", to: "companies#show", as: :company_dashboard
  resources :tasks
  patch "accept-task", to: "tasks#accept_task", as: :accept_task
  get "complete-task", to: "tasks#complete", as: :complete_task
  resources :gazelle_runners
  resources :companies do
    resources :tasks, only: [ :new, :show, :create, :destroy ]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
get 'design', to: 'pages#design'
end

app/views/pages/design.html.erb
<!-- search bar -->
<div class="container">
  <div class="row">
    <div class="col-sm-offset-3 col-sm-6">
      <div class="search-container">
        <input type="text" class="search-bar" id="user-input" placeholder="">
        <a href="#" class="search-btn">Search</a>
      </div>
    </div>
  </div>
</div>

<!-- button -->

<a href="#" class="btn-main">Become a gazelle</a>

app/views/pages/home.html.erb
<div class="bg">
<div class="layer">
<div class="headline-container">
<h1>The convenient & fast way to get help around the office</h1>
<h2>Get quick help from our friendly & efficient gazelles</h2>
</div>

<div class="container">
  <div class="row">
    <div class="col-sm-6">
      <% if current_user && current_user.company %>
        <%= form_tag(new_company_task_path(current_user.company), method: "get", class: "form-inline") do %>
          <div class="home-search-container shared-search-container">
          <%= text_field_tag :search, params[:search], placeholder: "What do you want done?", class: "search-bar", id: "search-bar" %>
          <%= button_tag '', {class: 'search-btn'} do %><i class="fas fa-arrow-right"></i><% end %>
          </div>
        <% end %>
        <% elsif current_user && current_user.gazelle_runner %>
        <% controller.redirect_to tasks_path %>
        <% else %>
         <br>
         <br>
         <br>
      <% end %>
    </div>
  </div>
</div>
</div>
</div>