config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'pages#home'
  resources :companies, only: [ :new, :create, :destroy, :edit]
  get "company-dashboard", to: "companies#show", as: :company_dashboard
  resources :tasks
  patch "accept-task", to: "tasks#accept_task", as: :accept_task
  get "complete-task", to: "tasks#complete", as: :complete_task
  resources :gazelle_runners
  resources :companies do
    resources :tasks, only: [ :new, :show, :create, :destroy ]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
get 'design', to: 'pages#design'
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy
  has_many :locations
  validates :name, presence: true, uniqueness: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def self.search(search)
    where("tasks ILIKE ?", "%#{search}%")
  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
    skip_before_action :authenticate_user!, only: [:show, :index]
    before_action :set_company, only: [ :edit, :update, :destroy]

  def index
    @companies = Company.all
    if params[:search]
      @companies = Company.search(params[:search]).order("created_at DESC")
    else
      @companies = Company.all.order("created_at DESC")
    end
  end

  def new
    @company = Company.new
  end

  def show
    @company = current_user.company
  end


  def edit
  end

  def update
    @company.update(company_params)
    redirect_to company_path(@company)
  end

  def destroy
    @company.destroy
    redirect_to company_path
  end

  private

  def company_params
    params.require(:company).require(:user_id).permit(:name)
  end


    def set_company
      @company = Company.find(params[:id])
    end
  end

app/views/companies/_form.html.erb
<%= simple_form_for(@company) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>


<h1>Company index</h1>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="t-bar-company-dashboard">
  <div class= "stat-text-center">
    <h1><%= @company.name%> Task Dashboard</h1>
  </div>
  </div>
  <div class="row">
    <% @company.tasks.order(created_at: :desc).each do |task| %>
    <div class="col-xs-12 col-sm-6 col-lg-10 col-lg-offset-1">
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= image_path task.photo %>');">
        <div class="task-status-dash">
          <% if task.state == "pending" %>
            <p class="company-task-status-pending">Your task will be assigned to a gazelle shortly</p>
             <% elsif task.state == "assigned" %>
            <p class="company-task-status-assigned">Your gazelle is on its way</p>
            <% else %>
            <p class="company-task-status-completed">Task has been completed</p>
          <% end %>
        </div>
        <div class="card-description">
          <h2><%= task.title.capitalize %></h2>
          <% if task.state == "pending" %>
          <p>Your gazelle will be assigned shortly</p>
          <% elsif task.state == "assigned" %>
            <% if task.gazelle_runner %>
              <p>Your gazelle will be <%= task.gazelle_runner.first_name %></p>
            <% end %>
            <% else %>
            <% if task.gazelle_runner %>
              <p>Your gazelle was <%= task.gazelle_runner.first_name %></p>
            <% end %>
          <% end %>
          <p>Total price: <%= task.cost_per_hour * task.task_time %> </p>
        </div>
        <img class="card-user"> <%=  %>
        <%= link_to "", company_task_path(@company, task), class: "card-link" %>
      </div>
    </div>
    <% end %>
  </div>